<?PHP

@ $fp = fopen('data.txt', 'w');
if (!$fp)
{
    echo 'Cannot generate message file';
    exit;
}
else
{
$outputstring  = 'Hello, i have been generated by the button';
fwrite($fp, $outputstring);
Echo "Message inserted";
}
?>
